<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Version>0.3.1</Version>
    <Company>Fezcode</Company>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NuGetAudit>true</NuGetAudit>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Airlift.Desktop' Or '$(MSBuildProjectName)' == 'Airlift.Cli'">
    <None Include="$(MSBuildThisFileDirectory)../LICENSE.txt" Link="LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>


