import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, Box, Check, ChevronDown, ChevronRight, CircleHelp, Compass, Download, Gamepad2, Globe2, Layers3, LayoutGrid, Library, List, LoaderCircle, Monitor, Package, Pause, Play, Plus, RefreshCw, Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, Terminal, Trash2, X } from 'lucide-react';
import { apps, initialState, labels, readState, size, type Action, type App, type State } from './model';
import './styles.css';
import { Sources } from './Sources';

type Page = 'Discover' | 'My library' | 'Updates' | 'Downloads' | 'Collections' | 'Sources' | 'Settings';
const categories = ['All apps', 'Productivity', 'Developer tools', 'Creative', 'Media', 'Utilities', 'Gaming'];
function AppIcon({ app, small = false }: { app: App; small?: boolean }) { return <div className={`app-icon ${small ? 'small' : ''}`} style={{ '--app-color': app.color } as React.CSSProperties}>{app.icon ? <img src={app.icon} alt=""/> : <Package/>}</div>; }
function Airlift() {
  const [page, setPage] = useState<Page>('Discover');
  const [category, setCategory] = useState('All apps');
  const [query, setQuery] = useState('');
  const [platform, setPlatform] = useState('windows');
  const [state, setState] = useState<State>(readState);
  const [selected, setSelected] = useState<App | null>(null);
  const [pending, setPending] = useState<{ app: App; action: Action } | null>(null);
  const [toast, setToast] = useState('');
  const [layout, setLayout] = useState('grid');
  const [sort, setSort] = useState('curated');
  const [collection, setCollection] = useState('Everyday essentials');
  const search = useRef<HTMLInputElement>(null);
  const dialog = useRef<HTMLDialogElement>(null);
  const confirmDialog = useRef<HTMLDialogElement>(null);
  const notify = (message: string) => setToast(message);
  const navigate = (next: Page) => { setPage(next); setQuery(''); setCategory('All apps'); };
  useEffect(() => { try { localStorage.setItem('airlift-preview-v1', JSON.stringify(state)); } catch { setToast('Browser storage is unavailable. Changes will last for this session.'); } }, [state]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer); }, [toast]);
  useEffect(() => {
    const listener = (e: KeyboardEvent) => { if ((e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'k') { e.preventDefault(); search.current?.focus(); } };
    window.addEventListener('keydown', listener); return () => window.removeEventListener('keydown', listener);
  }, []);
  useEffect(() => { if (selected) dialog.current?.showModal(); else dialog.current?.close(); }, [selected]);
  useEffect(() => { if (pending) confirmDialog.current?.showModal(); else confirmDialog.current?.close(); }, [pending]);
  useEffect(() => {
    const timer = setInterval(() => setState(current => {
      const active = current.jobs.find(j => j.status === 'running');
      if (!active) return current;
      const progress = Math.min(100, active.progress + 8);
      const installed = { ...current.installed };
      const app = apps.find(a => a.id === active.appId)!;
      if (progress === 100) {
        if (active.action === 'install' || active.action === 'update') installed[app.id] = app.version;
        if (active.action === 'uninstall') delete installed[app.id];
      }
      return { ...current, installed, jobs: current.jobs.map(j => j.id === active.id ? { ...j, progress, status: progress === 100 ? 'done' : 'running' } : j) };
    }), 500);
    return () => clearInterval(timer);
  }, []);
  const updates = apps.filter(a => state.installed[a.id] && state.installed[a.id] !== a.version && !state.pinned.includes(a.id));
  const activeJobs = state.jobs.filter(j => j.status === 'running' || j.status === 'paused');
  const enqueue = (app: App, action: Action) => {
    if (platform !== 'windows') return notify('This catalog contains Windows Forge packages. Other platform packages have not been published here.');
    setState(s => {
      if (s.jobs.some(j => j.appId === app.id && ['running', 'paused'].includes(j.status))) return s;
      return { ...s, jobs: [...s.jobs, { id: crypto.randomUUID(), appId: app.id, action, progress: 0, status: 'running' }] };
    });
    setPending(null); notify(`${app.name} added to the preview queue`);
  };
  const busy = (app: App) => activeJobs.some(j => j.appId === app.id);
  const actionButton = (app: App) => <button className={`get-button ${state.installed[app.id] ? 'installed' : ''}`} disabled={busy(app) || platform !== 'windows'} onClick={e => { e.stopPropagation(); state.installed[app.id] ? setSelected(app) : setPending({ app, action: 'install' }); }}>{busy(app) ? <LoaderCircle className="spin" size={14}/> : state.installed[app.id] ? <Check size={14}/> : <Plus size={14}/>} {busy(app) ? 'Queued' : state.installed[app.id] ? 'Manage' : 'Get'}</button>;
  let visible = apps.filter(a => (category === 'All apps' || a.category === category) && `${a.name} ${a.description} ${a.category}`.toLowerCase().includes(query.toLowerCase()) && a.platforms.includes(platform));
  if (page === 'My library') visible = visible.filter(a => state.installed[a.id]);
  if (page === 'Updates') visible = visible.filter(a => updates.includes(a));
  if (sort === 'name') visible = [...visible].sort((a, b) => a.name.localeCompare(b.name));
  const collectionApps = collection === 'The creative desk' ? apps.filter(a => ['Creative', 'Productivity'].includes(a.category)) : collection === 'After hours' ? apps.filter(a => ['Media', 'Gaming'].includes(a.category)) : apps.filter(a => ['clockt', 'Hisashi', 'Atelier', 'pidi'].includes(a.name));
  const title = page === 'Discover' ? 'Good tools. Great possibilities.' : page === 'My library' ? 'Your apps, all together.' : page === 'Updates' ? 'Keep a good thing going.' : page === 'Downloads' ? 'Everything in motion.' : page === 'Collections' ? 'A better setup starts here.' : page === 'Sources' ? 'Know where your apps come from.' : 'Make Airlift your own.';
  const subtitle = page === 'Discover' ? 'Discover thoughtfully built apps. Make your computer feel like yours.' : page === 'My library' ? 'Manage versions, pin your favorites, and make room for what’s next.' : page === 'Updates' ? 'Review what’s new and update on your terms.' : page === 'Downloads' ? 'Follow every download, installation, and update in one place.' : page === 'Collections' ? 'Thoughtful combinations of apps, ready for your workflow.' : page === 'Sources' ? 'A clear view of the catalogs behind your library.' : 'A few thoughtful defaults. The rest is up to you.';
  return <div className="shell">
    <aside className="sidebar">
      <a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('Discover'); }}><span className="brand-mark"><img src="/brand/airlift.svg" alt=""/></span><span>airlift<span className="byline">BY FEZCODE</span></span></a>
      <div className="workspace"><span className="workspace-icon"><Layers3 size={16}/></span><div>Personal workspace<span>Your apps. Your space.</span></div><ChevronDown size={14}/></div>
      <span className="nav-label">WORKSPACE</span>
      <nav>{([{ name: 'Discover', icon: Compass }, { name: 'My library', icon: Library }, { name: 'Updates', icon: RefreshCw }, { name: 'Downloads', icon: ArrowDownToLine }] as const).map(({ name, icon: Icon }) => <button key={name} className={page === name ? 'active' : ''} onClick={() => navigate(name)}><Icon size={18}/>{name}{name === 'Updates' && updates.length > 0 && <span className="count">{updates.length}</span>}{name === 'Downloads' && activeJobs.length > 0 && <span className="count">{activeJobs.length}</span>}</button>)}</nav>
      <span className="nav-label second">ORGANIZE</span>
      <nav><button className={page === 'Collections' ? 'active' : ''} onClick={() => navigate('Collections')}><Layers3 size={18}/>Collections</button><button className={page === 'Sources' ? 'active' : ''} onClick={() => navigate('Sources')}><Globe2 size={18}/>Sources<span className="subtle-count">1</span></button></nav>
      <div className="sidebar-bottom"><div className="forge-note"><span className="forge-emblem"><Box size={18}/></span><span>Built for your ecosystem<small>Powered by Forge</small></span><ArrowUpRight size={13}/></div><nav><button className={page === 'Settings' ? 'active' : ''} onClick={() => navigate('Settings')}><Settings2 size={18}/>Settings</button><button onClick={() => notify('Design preview · Ctrl / ⌘ K to search · App operations are simulated.')}><CircleHelp size={18}/>Help & shortcuts<kbd>?</kbd></button></nav><div className="profile"><span className="avatar">F</span><div>Fezcode<small>Local workspace</small></div><span className="online-dot"/></div></div>
    </aside>
    <div className="main-shell"><header className="topbar"><div className="breadcrumb">Workspace<ChevronRight size={13}/><span>{page}</span></div><label className="search"><Search size={16}/><input ref={search} aria-label="Search apps" placeholder="Search apps, tools, possibilities…" value={query} onChange={e => { setQuery(e.target.value); if (!['Discover', 'My library', 'Updates'].includes(page)) setPage('Discover'); }}/><kbd>⌘ K</kbd></label><span className="preview-badge"><span/>Design preview</span></header>
    <main><div className="page-heading"><div><div className="eyebrow">{page === 'Discover' ? 'A LITTLE DISCOVERY GOES A LONG WAY' : `YOUR WORKSPACE / ${page.toUpperCase()}`}</div><h1>{title}</h1><p>{subtitle}</p></div><label className="platform-picker"><Monitor size={15}/><select aria-label="Package platform" value={platform} onChange={e => setPlatform(e.target.value)}><option value="windows">Windows</option><option value="macos">macOS</option><option value="linux">Linux</option></select><ChevronDown size={13}/></label></div>
    {page === 'Discover' && !query && <><section className="hero"><div className="hero-copy"><span className="feature-tag"><Sparkles size={12}/> THE FEZCODE COLLECTION</span><h2>Small apps.<br/>A big lift.</h2><p>Less friction. More doing. Meet independent tools<br className="desktop-break"/> that make the everyday a little extraordinary.</p><button className="primary" onClick={() => { navigate('Collections'); setCollection('Everyday essentials'); }}>Find your essentials<ArrowRight size={16}/></button><div className="hero-caption"><span className="mini-line"/>Thoughtfully made. Yours to explore.</div></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit orbit-three"/><div className="art-grid"/><div className="floating-icon fi-one"><AppIcon app={apps[0]}/><span>WRITE</span></div><div className="floating-icon fi-two"><AppIcon app={apps[2]}/><span>BUILD</span></div><div className="floating-icon fi-three"><AppIcon app={apps[4]}/><span>UNWIND</span></div><div className="art-center"><img src="/brand/airlift.svg" alt=""/></div><span className="star star-one">✦</span><span className="star star-two">+</span><span className="art-coordinates">35°  →  YOUR NEXT GREAT TOOL</span></div></section><div className="trust-strip"><span><Box size={15}/>{apps.length} independent apps</span><span><ShieldCheck size={15}/>Your setup, your control</span><span><Terminal size={15}/>Made by Fezcode</span><button onClick={() => navigate('Sources')}>Meet your source<ArrowUpRight size={13}/></button></div></>}
    {['Discover', 'My library', 'Updates'].includes(page) && <><div className="section-heading"><h2>{page === 'Discover' ? 'Find your next favorite' : page === 'My library' ? 'Installed in this preview' : 'Available updates'}<span>{visible.length}</span></h2><div className="view-controls"><button aria-label="Grid view" className={layout === 'grid' ? 'selected' : ''} onClick={() => setLayout('grid')}><LayoutGrid size={15}/></button><button aria-label="List view" className={layout === 'list' ? 'selected' : ''} onClick={() => setLayout('list')}><List size={17}/></button></div></div><div className="filter-row"><div className="category-tabs">{categories.map(c => <button key={c} className={category === c ? 'selected' : ''} onClick={() => setCategory(c)}>{c}</button>)}</div><label className="sort"><SlidersHorizontal size={13}/><select aria-label="Sort apps" value={sort} onChange={e => setSort(e.target.value)}><option value="curated">Curated</option><option value="name">A–Z</option></select></label></div>
    {visible.length > 0 ? <div className={`app-grid ${layout === 'list' ? 'list-layout' : ''}`}>{visible.map(app => <article key={app.id} className="app-card"><div className="card-top"><button className="app-identity" onClick={() => setSelected(app)}><AppIcon app={app}/><div><h3>{app.name}</h3><span>{app.category}</span></div></button>{actionButton(app)}</div><button className="card-description" onClick={() => setSelected(app)}>{app.description}</button><div className="card-footer"><span>Fezcode <span className="publisher-dot">·</span> <span>v{app.version}</span></span><span className="platform-dot"><Monitor size={11}/>{size(app)}</span></div></article>)}</div> : <div className="empty"><Package size={36}/><h3>{query ? 'No matches this time.' : platform !== 'windows' ? 'A little more runway needed.' : page === 'My library' ? 'Your next setup starts with one app.' : 'You’re all caught up.'}</h3><p>{platform !== 'windows' ? `The local Forge catalog has no ${platform === 'macos' ? 'macOS' : 'Linux'} packages yet. Airlift’s desktop design supports all three platforms.` : query ? 'Try a different search or category.' : page === 'My library' ? 'Explore the catalog and try an installation. All changes stay in this preview.' : 'No unpinned preview apps have a newer catalog version.'}</p><button className="secondary" onClick={() => { navigate('Discover'); setPlatform('windows'); }}>Explore Windows apps<ArrowRight size={14}/></button></div>}
    {page === 'Discover' && !query && <section className="collection-banner"><div className="collection-symbol"><Layers3 size={24}/></div><div><h3>A fresh start, without the setup.</h3><p>Your favorite apps, bundled into collections. Get back to what matters.</p></div><button onClick={() => navigate('Collections')}>Explore collections<ArrowRight size={15}/></button></section>}</>}
    {page === 'Downloads' && <section className="panel"><div className="panel-heading"><h2>Activity <span>{state.jobs.length}</span></h2><button className="text-button" onClick={() => setState(s => ({ ...s, jobs: s.jobs.filter(j => j.status !== 'done' && j.status !== 'cancelled') }))}>Clear completed</button></div><div className="inline-note">Preview activity is simulated. No installers run on your computer.</div>{state.jobs.length === 0 ? <div className="empty"><ArrowDownToLine size={36}/><h3>A clear runway.</h3><p>Your downloads and installations will appear here.</p><button className="secondary" onClick={() => navigate('Discover')}>Find an app<ArrowRight size={14}/></button></div> : state.jobs.map(job => { const app = apps.find(a => a.id === job.appId)!; return <div className="job" key={job.id}><AppIcon app={app} small/><div className="job-main"><h3>{app.name}<span>{labels[job.action]}</span></h3><div className="progress"><span style={{ width: `${job.progress}%` }}/></div><small>{job.status === 'done' ? 'Completed in preview' : job.status === 'cancelled' ? 'Cancelled' : job.status === 'paused' ? 'Paused' : `${job.progress}% · Simulating ${job.action}`}</small></div>{['running', 'paused'].includes(job.status) ? <><button className="icon-button" aria-label={`${job.status === 'paused' ? 'Resume' : 'Pause'} ${app.name}`} onClick={() => setState(s => ({ ...s, jobs: s.jobs.map(j => j.id === job.id ? { ...j, status: j.status === 'paused' ? 'running' : 'paused' } : j) }))}>{job.status === 'paused' ? <Play size={16}/> : <Pause size={16}/>}</button><button className="icon-button" aria-label={`Cancel ${app.name}`} onClick={() => setState(s => ({ ...s, jobs: s.jobs.map(j => j.id === job.id ? { ...j, status: 'cancelled' } : j) }))}><X size={16}/></button></> : <Check size={17} className="muted"/>}</div>; })}</section>}
    {page === 'Collections' && <><div className="collections-grid">{['Everyday essentials', 'The creative desk', 'After hours'].map((name, i) => <button key={name} className={`collection-card collection-${i} ${name === collection ? 'chosen' : ''}`} onClick={() => setCollection(name)}><span className="collection-number">COLLECTION 0{i + 1}</span>{i === 0 ? <Layers3 size={38}/> : i === 1 ? <Sparkles size={38}/> : <Gamepad2 size={38}/>}<h2>{name}</h2><p>{['A smoother day, from the first click.', 'Room for your next big idea.', 'Clock out. Tune in. Press play.'][i]}</p><span className="collection-link">Explore collection<ArrowUpRight size={16}/></span></button>)}</div><div className="section-heading"><h2>{collection}<span>{collectionApps.length} apps</span></h2><button className="secondary" disabled={platform !== 'windows' || collectionApps.every(a => state.installed[a.id] || busy(a))} onClick={() => { collectionApps.filter(a => !state.installed[a.id]).forEach(a => enqueue(a, 'install')); navigate('Downloads'); }}>Try collection<Plus size={15}/></button></div><div className="app-grid">{collectionApps.map(app => <article className="app-card compact-card" key={app.id}><div className="card-top"><button className="app-identity" onClick={() => setSelected(app)}><AppIcon app={app}/><div><h3>{app.name}</h3><span>{app.category}</span></div></button>{actionButton(app)}</div><p>{app.tagline}</p></article>)}</div></>}
    <div hidden={page !== 'Sources'}><Sources/></div>
    {page === 'Settings' && <section className="panel settings-panel"><h2>Your preferences</h2><div className="setting-row"><div><h3>Automatic updates</h3><p>Save your preferred update policy for this preview.</p></div><button role="switch" aria-label="Automatic updates" aria-checked={state.autoUpdate} className={`toggle ${state.autoUpdate ? 'on' : ''}`} onClick={() => setState(s => ({ ...s, autoUpdate: !s.autoUpdate }))}><span/></button></div><div className="setting-row"><div><h3>Try the update workflow</h3><p>Load sample installed versions of Descry and clockt to explore updates.</p></div><button className="secondary" onClick={() => { setState(s => ({ ...s, installed: { ...s.installed, [apps[0].id]: '0.86.0', [apps[2].id]: '0.5.12' } })); navigate('Updates'); }}>Load sample library</button></div><div className="setting-row"><div><h3>Reset the preview</h3><p>Clear simulated installs, activity, version pins, and preferences.</p></div><button className="secondary" onClick={() => { setState(initialState); notify('Preview reset. Your computer’s apps are unchanged.'); }}>Reset preview</button></div><div className="inline-note">Airlift 0.1 · Interactive design prototype. Package operations and preferences do not change your operating system.</div></section>}
    <footer><span><span className="online-dot"/>Local catalog · {apps.length} apps</span><span>A little lift for your everyday.</span><span>Made with intention <ArrowUpRight size={12}/></span></footer>
    </main></div>
    <dialog ref={dialog} className="detail-dialog" onCancel={() => setSelected(null)} onClick={e => { if (e.target === dialog.current) setSelected(null); }}>{selected && <><div className="dialog-top"><span>APP OVERVIEW</span><button className="icon-button" aria-label="Close app details" onClick={() => setSelected(null)}><X size={19}/></button></div><div className="detail-title"><AppIcon app={selected}/><div><h2>{selected.name}</h2><p>{selected.tagline}</p></div></div><p className="detail-description">{selected.description}</p><div className="detail-tags"><span><Monitor size={13}/>Windows package</span><span>{selected.category}</span><span>v{selected.version}</span></div><div className="detail-facts"><div><span>Publisher</span><strong>{selected.publisher}</strong></div><div><span>Package</span><strong>Forge installer</strong></div><div><span>Local download size</span><strong>{size(selected)}</strong></div><div><span>Manifest</span><code>{selected.manifest}</code></div>{state.installed[selected.id] && <div><span>Preview installed version</span><strong>{state.installed[selected.id]}</strong></div>}</div><div className="inline-note">Design preview — actions below simulate the package lifecycle.</div><div className="detail-actions">{state.installed[selected.id] ? <><button className="secondary" onClick={() => setState(s => ({ ...s, pinned: s.pinned.includes(selected.id) ? s.pinned.filter(id => id !== selected.id) : [...s.pinned, selected.id] }))}>{state.pinned.includes(selected.id) ? 'Unpin version' : 'Pin version'}</button>{state.installed[selected.id] !== selected.version && !state.pinned.includes(selected.id) && <button className="primary" disabled={busy(selected) || platform !== 'windows'} onClick={() => enqueue(selected, 'update')}>Update<RefreshCw size={14}/></button>}<button className="danger-button" disabled={busy(selected) || platform !== 'windows'} onClick={() => setPending({ app: selected, action: 'uninstall' })}><Trash2 size={14}/>Uninstall</button></> : <button className="primary" disabled={busy(selected) || platform !== 'windows'} onClick={() => setPending({ app: selected, action: 'install' })}><Plus size={15}/>Install app</button>}<button className="secondary" disabled={busy(selected) || platform !== 'windows'} onClick={() => enqueue(selected, 'download')}><Download size={14}/>Download only</button></div></>}</dialog>
    <dialog ref={confirmDialog} className="confirm-dialog" onCancel={() => setPending(null)}>{pending && <><div className="dialog-top"><span>PREVIEW {pending.action.toUpperCase()}</span><button className="icon-button" aria-label="Close confirmation" onClick={() => setPending(null)}><X size={19}/></button></div><AppIcon app={pending.app}/><h2>{labels[pending.action]} {pending.app.name}?</h2><p>{pending.action === 'uninstall' ? 'Remove this app from your preview library. Your actual apps, settings, and personal data stay untouched.' : 'Try the installation flow and add this app to your preview library. No files will be downloaded or installed on your computer.'}</p><div className="confirm-details"><span>Version</span><strong>{pending.app.version}</strong><span>Source</span><strong>Workhammer / Forge</strong><span>Mode</span><strong>Simulated operation</strong></div><div className="detail-actions"><button className="secondary" onClick={() => setPending(null)}>Cancel</button><button className={pending.action === 'uninstall' ? 'danger-button' : 'primary'} onClick={() => enqueue(pending.app, pending.action)}>{labels[pending.action]} in preview<ArrowRight size={15}/></button></div></>}</dialog>
    {toast && <div className="toast" role="status"><Check size={16}/>{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={14}/></button></div>}
  </div>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><Airlift/></React.StrictMode>);

